language: csharp
solution: ./FreecraftCore.Serializer.sln

install:
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory tests/testrunner
  - nuget restore FreecraftCore.Serializer.sln

before_script:
  - chmod +x ./tests/RunTests.sh
  - chmod +x ./Build.sh

script:
  - ./Build.sh
  - cd "$TRAVIS_BUILD_DIR/tests"
  - ./RunTests.sh
  - cd "$TRAVIS_BUILD_DIR"